site_name: Python for Beginner
# site_url: the page by GitHub Page
docs_dir: docs
theme:
  name: material
  logo: images/logo.png
  features:
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lei-wu-58794a73
    - icon: fontawesome/solid/paper-plane
      link: mailto:<leiwuinfo@gmail.com>
    - icon: fontawesome/brands/github
      link: https://github.com/leiwu84

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - caption

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Use: use.md
  - Code: code.md
  - Style Guidelines: style_guidelines.md
